name: CreateRelease
'on':
  push:
    tags:
    - '*'
jobs:
  createRelease:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: Install pkl cli
      run: |-
        curl -L -o pkl https://github.com/apple/pkl/releases/download/0.25.2/pkl-linux-amd64
        chmod +x pkl
        ./pkl --version
    - name: Package pkl module
      env:
        VERSION: ${{ github.ref_name }}
      run: ./pkl project package
    - name: Rename pkl module
      env:
        VERSION_NUMBER: ${{ github.ref_name#*@ }}
      run: mv .out/com.github.action@${{ env.VERSION_NUMBER }}/pkl-gha@${{ env.VERSION_NUMBER }} .out/com.github.action@${{ env.VERSION_NUMBER }}/com.github.action@${{ env.VERSION_NUMBER }}
    - uses: softprops/action-gh-release@v1
      with:
        files: .out/com.github.action@${{ env.VERSION_NUMBER }}/*
        prerelease: 'true'
        draft: 'true'
